services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mariadb -u${MARIADB_USER} -p${MARIADB_PASSWORD} -e 'SELECT 1' ${MARIADB_DATABASE} || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    networks: [wpnet]

  wordpress:
    image: wordpress:6.6-apache
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', false);
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"   # put your reverse proxy in front of this
    healthcheck:
      test: ["CMD","curl","-f","http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 10
    networks: [wpnet]

volumes:
  db_data:
  wp_data:

networks:
  wpnet:
    driver: bridge
